# version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: heartbuddy-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: heartbuddy-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/heartbuddy
      JWT_SECRET: heartbuddy_secret
      ADMIN_EMAIL: admin@heartbuddy.com
      ADMIN_PASSWORD: Admin@123
    depends_on:
      - mongo
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: heartbuddy-frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://backend:5000/api
    depends_on:
      - backend

volumes:
  mongo_data:
